name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger only on main branch pushes
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Read Version
        id: version
        run: |
          VERSION=$(cat backend/version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Increment Build Number
        id: versioning
        run: |
          IFS='.' read -r MAJOR MINOR BUILD < backend/version.txt
          NEW_BUILD=$((BUILD + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_BUILD"
          echo "$NEW_VERSION" > version.txt
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit Updated Version
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add backend/version.txt
          git commit -m "Bump version to $NEW_VERSION"
          git push

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd backend
          docker build -t adiroth23/ci-cd-analyzer-backend:${{ env.NEW_VERSION }} .
          docker tag adiroth23/ci-cd-analyzer-backend:${{ env.NEW_VERSION }} adiroth23/ci-cd-analyzer-backend:latest
          docker push adiroth23/ci-cd-analyzer-backend:${{ env.NEW_VERSION }}
          docker push adiroth23/ci-cd-analyzer-backend:latest
